apiVersion: v2
name: order-service
description: A Helm chart for Kubernetes

type: application

version: 0.5.0
appVersion: 0.10.0

dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - order-service-database
